### ISSUE TITLE
Missing dependencies in 4.1.0

### ISSUE THREAD

**Issue by uzairfaisal** [epegzz/sass-vars-loader#28]
For the latest version (4.1.0), you're missing dependencies `typescript` and `require-from-string`. See https://github.com/epegzz/sass-vars-loader/blob/184ab81ea5c8e246196fc7788f36f8f18dd0c028/src/utils/readVarsFromTypescriptFiles.js - you're requiring them during runtime but you'll notice that you have those 2 modules as dev dependencies in your package.json.

Here's the failing logs:

```
Module build failed (from ./node_modules/@epegzz/sass-vars-loader/src/sassVarsLoader.js):
Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\334835170\SrcCode\pi-frontend\node_modules\@epegzz\sass-vars-loader\src\utils\readVarsFromTypescriptFiles.js:2:12)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\334835170\SrcCode\pi-frontend\node_modules\@epegzz\sass-vars-loader\src\sassVarsLoader.js:4:37)
```

**Comment by epegzz** [comment]
Oooops, you're absolutely right 😬 
I just released a fixed version `v4.1.1`

Thank you for the feedback! ❤️
