### ISSUE TITLE
Assertion error on precommit hook

### ISSUE THREAD

**Issue by netstuff** [epegzz/sass-vars-loader#37]
Hello.
I wrote some useful code for this library (netstuff/sass-vars-loader) and want to commit changes to new branch to create a pull-request for you. But on committing to I get an error:
```
prettier-eslint [ERROR]: There was trouble creating the ESLint CLIEngine.
prettier-eslint-cli [ERROR]: There was an error formatting "src/sassVarsLoader.test.js": 
  AssertionError [ERR_ASSERTION]: 'basePath' should be an absolute path.
      at new IgnorePattern (/Users/netstuff/Sites/forks/sass-vars-loader/node_modules/eslint/lib/cli-engine/config-array/ignore-pattern.js:178:9)
      at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/netstuff/Sites/forks/sass-vars-loader/node_modules/eslint/lib/cli-engine/config-array-factory.js:651:49)
      at _normalizeObjectConfigDataBody.next (<anonymous>)
      at ConfigArrayFactory._normalizeObjectConfigData (/Users/netstuff/Sites/forks/sass-vars-loader/node_modules/eslint/lib/cli-engine/config-array-factory.js:594:20)
      at _normalizeObjectConfigData.next (<anonymous>)
      at createConfigArray (/Users/netstuff/Sites/forks/sass-vars-loader/node_modules/eslint/lib/cli-engine/config-array-factory.js:338:25)
      at ConfigArrayFactory.create (/Users/netstuff/Sites/forks/sass-vars-loader/node_modules/eslint/lib/cli-engine/config-array-factory.js:393:16)
      at createBaseConfigArray (/Users/netstuff/Sites/forks/sass-vars-loader/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:96:48)
      at new CascadingConfigArrayFactory (/Users/netstuff/Sites/forks/sass-vars-loader/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:211:30)
      at new CLIEngine (/Users/netstuff/Sites/forks/sass-vars-loader/node_modules/eslint/lib/cli-engine/cli-engine.js:563:36)
```

which repeats 25 times!

Please help me to resolve this issue!

**Comment by epegzz** [comment]
My first guess is that at some point you need to use `path.resolve(path)` instead of `path`.
I'm not really sure where though 🤔

**Comment by epegzz** [comment]
Did you define `ignorePatterns` anywhere for eslint? Maybe in a global eslint config?

**Comment by netstuff** [comment]
Ok. It was because I using `yarn`. On `npm` all works properly. Thank you very much!
